using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Godot_Generator_Avalonia.Models;
using Microsoft.Extensions.DependencyInjection;
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Controls;

namespace Godot_Generator_Avalonia.ViewModels;

/// <summary>
/// Shell: left navigation and current pane (config or generation panel).
/// </summary>
public partial class MainWindowViewModel : ViewModelBase
{
    private readonly Dictionary<GenerationModality, GenerationPanelViewModel> _panels;

    /// <summary>
    /// Creates the main window model with config and one view model per modality.
    /// </summary>
    public MainWindowViewModel(IServiceScopeFactory scopeFactory)
    {
        NavItems = new List<NavItem>
        {
            new NavItem("CogOutline", "Config"),
            new NavItem("ViewDashboardOutline", "Scenes"),
            new NavItem("Xml", "Code"),
            new NavItem("FileDocumentOutline", "Text"),
            new NavItem("ImageOutline", "Image"),
            new NavItem("Grid", "Sprites"),
            new NavItem("GestureTapButton", "Animations"),
            new NavItem("VolumeHigh", "Audio"),
            new NavItem("MovieOutline", "Video"),
            new NavItem("PaletteOutline", "Godot UI"),
            new NavItem("Atom", "Godot Physics"),
            new NavItem("Unity", "Godot Project"),
        };

        Config = new ConfigViewModel(scopeFactory);
        _panels = new Dictionary<GenerationModality, GenerationPanelViewModel>();
        foreach (GenerationModality m in Enum.GetValues<GenerationModality>())
        {
            _panels[m] = new GenerationPanelViewModel(scopeFactory, m);
        }

        // menu commands are generated by the [RelayCommand] source generator on the methods
    }

    [RelayCommand]
    private async Task NewProjectAsync()
    {
        // Create a new project placeholder: show save dialog to pick folder/file
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            var dlg = new SaveFileDialog { DefaultExtension = "", InitialFileName = "NewProject" };
            var path = await dlg.ShowAsync(w).ConfigureAwait(true);
            if (!string.IsNullOrWhiteSpace(path))
            {
                // TODO: implement project creation logic
                StatusMessage = $"New project: {path}";
            }
        }
    }

    [RelayCommand]
    private async Task OpenProjectAsync()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            var dlg = new OpenFileDialog { AllowMultiple = false };
            var res = await dlg.ShowAsync(w).ConfigureAwait(true);
            if (res?.Length > 0)
            {
                var path = res[0];
                // TODO: implement project open logic (load state, etc.)
                StatusMessage = $"Opened project: {path}";
            }
        }
    }

    [RelayCommand]
    private async Task SaveProjectAsync()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            var dlg = new SaveFileDialog { DefaultExtension = "", InitialFileName = "Project" };
            var path = await dlg.ShowAsync(w).ConfigureAwait(true);
            if (!string.IsNullOrWhiteSpace(path))
            {
                // TODO: implement project save logic
                StatusMessage = $"Saved project: {path}";
            }
        }
    }

    [RelayCommand]
    private void GenerateCurrent()
    {
        // If the current pane is a generation panel, execute its GenerateCommand
        if (CurrentPane is GenerationPanelViewModel gp)
        {
            var cmd = gp.GenerateCommand;
            if (cmd.CanExecute(null))
            {
                cmd.Execute(null);
            }
        }
    }

    [RelayCommand]
    private void Undo() { }

    [RelayCommand]
    private void Redo() { }

    [RelayCommand]
    private void Cut() { }

    [RelayCommand]
    private void Copy() { }

    [RelayCommand]
    private void Paste() { }

    [RelayCommand]
    private void Delete() { }

    [RelayCommand]
    private void SelectAll() { }

    [RelayCommand]
    private void ToggleDevTools() { }

    [RelayCommand]
    private void ForceReload() { }

    [RelayCommand]
    private void ResetZoom() { }

    [RelayCommand]
    private void ZoomIn() { }

    [RelayCommand]
    private void ZoomOut() { }

    [RelayCommand]
    private void ToggleFullscreen()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            w.WindowState = w.WindowState == WindowState.FullScreen ? WindowState.Normal : WindowState.FullScreen;
        }
    }

    [RelayCommand]
    private async Task About()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            var version = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "1.0.0";
            var dialog = new Window
            {
                Title = "About Godot Generator",
                Width = 360,
                Height = 200,
                CanResize = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                Content = new Avalonia.Controls.StackPanel
                {
                    Margin = new Avalonia.Thickness(24),
                    Spacing = 12,
                    Children =
                    {
                        new Avalonia.Controls.TextBlock { Text = "Godot Generator", FontSize = 20, FontWeight = Avalonia.Media.FontWeight.Bold, HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center },
                        new Avalonia.Controls.TextBlock { Text = $"Version: {version}", HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center },
                        new Avalonia.Controls.TextBlock { Text = "AI-powered Godot project generator\nwith multi-modal content creation.", TextAlignment = Avalonia.Media.TextAlignment.Center, HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center },
                    }
                }
            };
            await dialog.ShowDialog(w);
        }
    }

    [RelayCommand]
    private void OpenUserGuide()
    {
        OpenDocumentation();
    }

    /// <summary>Left menu items (index matches <see cref="SelectedNavIndex"/>).</summary>
    public IReadOnlyList<NavItem> NavItems { get; }

    /// <summary>Global configuration pane.</summary>
    public ConfigViewModel Config { get; }

    [ObservableProperty]
    private int _selectedNavIndex;

    /// <summary>Current right-hand content: config or a generation panel.</summary>
    public object CurrentPane => SelectedNavIndex switch
    {
        0 => Config,
        1 => _panels[GenerationModality.Scenes],
        2 => _panels[GenerationModality.Code],
        3 => _panels[GenerationModality.Text],
        4 => _panels[GenerationModality.Image],
        5 => _panels[GenerationModality.Sprites],
        6 => _panels[GenerationModality.Audio],
        7 => _panels[GenerationModality.Video],
        8 => _panels[GenerationModality.GodotUi],
        9 => _panels[GenerationModality.GodotPhysics],
        10 => _panels[GenerationModality.GodotProject],
        11 => _panels[GenerationModality.Animations],
        _ => Config,
    };

    partial void OnSelectedNavIndexChanged(int value)
    {
        OnPropertyChanged(nameof(CurrentPane));
    }

    private void ShowNavigation(int index) => SelectedNavIndex = index;

    /// <summary>
    /// Selects a navigation section from menu commands.
    /// </summary>
    [RelayCommand]
    private void SelectNavigation(int index)
    {
        if (index >= 0 && index < NavItems.Count)
        {
            ShowNavigation(index);
        }
    }

    [RelayCommand] private void ShowConfig() => ShowNavigation(0);
    [RelayCommand] private void ShowScenes() => ShowNavigation(1);
    [RelayCommand] private void ShowCode() => ShowNavigation(2);
    [RelayCommand] private void ShowText() => ShowNavigation(3);
    [RelayCommand] private void ShowImage() => ShowNavigation(4);
    [RelayCommand] private void ShowSprites() => ShowNavigation(5);
    [RelayCommand] private void ShowAnimations() => ShowNavigation(6);
    [RelayCommand] private void ShowAudio() => ShowNavigation(7);
    [RelayCommand] private void ShowVideo() => ShowNavigation(8);
    [RelayCommand] private void ShowGodotUi() => ShowNavigation(9);
    [RelayCommand] private void ShowGodotPhysics() => ShowNavigation(10);
    [RelayCommand] private void ShowGodotProject() => ShowNavigation(11);

    /// <summary>
    /// Reloads configuration in the settings shell.
    /// </summary>
    [RelayCommand]
    private void ReloadConfiguration()
    {
        Config.ReloadAllCommand.Execute(null);
    }

    /// <summary>
    /// Opens the project repository in the default system browser.
    /// </summary>
    [RelayCommand]
    private void OpenRepo()
    {
        try
        {
            var url = "https://github.com/Ozymandros/Godot-Generator-Avalonia";
            if (OperatingSystem.IsWindows())
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = url,
                    UseShellExecute = true
                });
            }
            else if (OperatingSystem.IsLinux())
            {
                System.Diagnostics.Process.Start("xdg-open", url);
            }
            else if (OperatingSystem.IsMacOS())
            {
                System.Diagnostics.Process.Start("open", url);
            }
        }
        catch
        {
            // best effort
        }
    }

    /// <summary>
    /// Opens the project documentation in the default system browser.
    /// </summary>
    [RelayCommand]
    private void OpenDocumentation()
    {
        try
        {
            var url = "https://github.com/Ozymandros/Godot-Generator-Avalonia/blob/master/README.md";
            if (OperatingSystem.IsWindows())
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = url,
                    UseShellExecute = true
                });
            }
            else if (OperatingSystem.IsLinux())
            {
                System.Diagnostics.Process.Start("xdg-open", url);
            }
            else if (OperatingSystem.IsMacOS())
            {
                System.Diagnostics.Process.Start("open", url);
            }
        }
        catch
        {
            // best effort
        }
    }

    /// <summary>
    /// Closes the desktop application.
    /// </summary>
    [RelayCommand]
    private void ExitApplication()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime)
        {
            lifetime.Shutdown();
        }
    }

    /// <summary>
    /// Window control: minimize the main window.
    /// </summary>
    [RelayCommand]
    private void Minimize()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            w.WindowState = WindowState.Minimized;
        }
    }

    /// <summary>
    /// Toggle maximize/restore for the main window.
    /// </summary>
    [RelayCommand]
    private void ToggleMaximize()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            w.WindowState = w.WindowState == WindowState.Maximized ? WindowState.Normal : WindowState.Maximized;
        }
    }

    /// <summary>
    /// Restore the main window.
    /// </summary>
    [RelayCommand]
    private void RestoreWindow()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            w.WindowState = WindowState.Normal;
        }
    }

    /// <summary>
    /// Close the main window.
    /// </summary>
    [RelayCommand]
    private void CloseWindow()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime lifetime && lifetime.MainWindow is Window w)
        {
            w.Close();
        }
    }
}
