<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <WasmEnableWebcil>false</WasmEnableWebcil>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.13.2" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.13.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GodotGenerator.Blazor.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GodotGenerator.Api\GodotGenerator.Api.csproj" />
    <ProjectReference Include="..\..\src\GodotGenerator.Application\GodotGenerator.Application.csproj" />
    <ProjectReference Include="..\..\src\GodotGenerator.Desktop.Contracts\GodotGenerator.Desktop.Contracts.csproj" />
  </ItemGroup>

</Project>
